# Generated by Django 5.2.10 on 2026-01-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casos_confirmados', models.IntegerField()),
                ('mortes', models.IntegerField()),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(max_length=50)),
                ('taxa_incidentes', models.FloatField(blank=True, null=True)),
                ('taxa_letalidade', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'registros',
            },
        ),
    ]
